version: "3.3"
services:
  mysqldb:
    image: mysql:8
    networks:
      - saludos-mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql 
    environment:
      - MYSQL_ROOT_USER: 789xx
      - MYSQL_ROOT_PASSWORD: 123456
      - MYSQL_DATABASE: saludos_22
      - MYSQL_USER: 789xx
      - MYSQL_PASSWORD: 123456
 
  saludar-service:
    image: saludar-service
    build:
      context: ./SaludarService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - saludos-mysql
    depends_on:
      - mysqldb

networks:
  saludos-mysql: